{
  _site {
    globalSeo{
      fallbackSeo {
        title
        twitterCard
        description
      }
      facebookPageUrl
      siteName
      titleSuffix
    }
    favicon {
      url
    }
  }
}
