{
  repairPage {
    description
    headings
    example {
      photo {
        url
        responsiveImage {
          srcSet
          src
          height
          sizes
          alt
        }
      }
    }
  }
}
