{
  home {
    copyright
    heroimage {
    	url
  	}
    introText
    pagelocation {
      latitude
      longitude
    }
    seoSettings {
      description
      image {
        url
        alt
        size
        height
        width
      }
      title
      twitterCard
    }
    subtitle
    title
    updatedAt
    phoneNumber
  }
}
